spring:
  datasource:
    url: jdbc:sqlserver://localhost:1401;database=CoreWebAPI
    username: "sa"
    password: "123bioIvd"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #    hikari:
  #      maximum-pool-size: 1

  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    show-sql: true
    hibernate:
      ddl-auto: update #create, create-drop, validate, and update
      use-new-id-generator-mappings: false